# Generated by Django 5.0.4 on 2026-05-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerTimeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MWL", "Muslim World League"),
                            ("ISNA", "Islamic Society of North America"),
                            ("Egypt", "Egyptian General Authority"),
                            ("Makkah", "Umm Al-Qura University"),
                            ("Karachi", "University of Islamic Sciences"),
                            ("Tehran", "Institute of Geophysics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fajr", models.TimeField()),
                ("sunrise", models.TimeField()),
                ("dhuhr", models.TimeField()),
                ("asr", models.TimeField()),
                ("maghrib", models.TimeField()),
                ("isha", models.TimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.country",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "method", "latitude", "longitude"],
                        name="prayers_pra_date_7a8b82_idx",
                    )
                ],
                "unique_together": {("latitude", "longitude", "date", "method")},
            },
        ),
    ]
