# Generated by Django 5.0.4 on 2026-05-08 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("dial_code", models.CharField(max_length=10)),
                ("is_supported", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="ProviderCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="0 = primary provider, higher = fallback"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="providers.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Provider Countries",
                "ordering": ["country", "priority"],
            },
        ),
        migrations.CreateModel(
            name="TelcoProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("voice", "Voice"),
                            ("both", "SMS & Voice"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "adapter_class",
                    models.CharField(
                        help_text="Full path to adapter class, e.g. apps.providers.adapters.twilio.TwilioAdapter",
                        max_length=255,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("account_sid", models.CharField(blank=True, max_length=500)),
                ("sender_id", models.CharField(blank=True, max_length=50)),
                ("base_url", models.URLField(blank=True)),
                ("auth_token", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("supports_voice", models.BooleanField(default=False)),
                ("voice_webhook_url", models.URLField(blank=True)),
                (
                    "cost_per_sms",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "cost_per_minute",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "countries",
                    models.ManyToManyField(
                        through="providers.ProviderCountry", to="providers.country"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="providercountry",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.telcoprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providercountry",
            unique_together={("provider", "country")},
        ),
    ]
