# Generated by Django 5.0.4 on 2026-05-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("summary", "Daily Summary"),
                            ("pre_adhan", "Pre-Adhan"),
                            ("adhan", "Adhan"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("call", "Phone Call"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prayer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fajr", "Fajr"),
                            ("dhuhr", "Dhuhr"),
                            ("asr", "Asr"),
                            ("maghrib", "Maghrib"),
                            ("isha", "Isha"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="providers.telcoprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_a3de53_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_2e04f4_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_8fa9d0_idx",
                    ),
                ],
            },
        ),
    ]
